obj-y		+= devices.o
obj-y		+= dmac-irq.o
obj-y		+= identify.o
obj-y		+= intc-irq.o
obj-y		+= irq.o
obj-y		+= memory.o
obj-y		+= prom.o
obj-y		+= reboot.o
obj-y		+= rom.o
obj-m		+= rom-sysfs.o
obj-y		+= scmd.o
obj-y		+= time.o

obj-y		+= cache.o
