obj-$(CONFIG_PS2_GS)		+= gif.o
obj-$(CONFIG_PS2_GS)		+= gs.o
obj-$(CONFIG_PS2_GS)		+= gs-irq.o
obj-$(CONFIG_PS2_GS)		+= gs-registers.o
obj-$(CONFIG_PS2_GS)		+= gs-sysfs.o

obj-m				+= iop-heap.o
obj-m				+= iop-irq.o
obj-m				+= iop-memory.o
obj-m				+= iop-module.o
obj-m				+= iop-registers.o
obj-m				+= sif.o

iop-module-objs			+= iop-module-request.o iop-module-patch.o
